import type { ForgeDiagnosticCode } from "./codes.js";
import type { ForgeDiagnosticDefinition } from "./types.js";

export const DIAGNOSTIC_CATALOG = Object.freeze({
  CFG_SCHEMA_VERSION_MISSING: {
    code: "CFG_SCHEMA_VERSION_MISSING",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "The configuration schema version is missing.",
    message: "The configuration must declare schemaVersion.",
    suggestion: 'Add "schemaVersion": "1" at the configuration root.',
    fixable: true,
  },
  CFG_SCHEMA_VERSION_UNSUPPORTED: {
    code: "CFG_SCHEMA_VERSION_UNSUPPORTED",
    severity: "error",
    category: "compatibility",
    source: "compatibility",
    summary: "The configuration schema version is unsupported.",
    message: "This schemaVersion is not supported by this Forge version.",
    suggestion:
      'Use schemaVersion "1" or a Forge version that supports the file.',
    fixable: false,
  },
  CFG_UNKNOWN_FIELD: {
    code: "CFG_UNKNOWN_FIELD",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "The configuration contains an unknown field.",
    message: "This field is not defined by the configuration contract.",
    suggestion: "Remove the field or check its spelling and schema version.",
    fixable: false,
  },
  CFG_REQUIRED_FIELD_MISSING: {
    code: "CFG_REQUIRED_FIELD_MISSING",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "A required field is missing.",
    message: "A required configuration field is missing.",
    suggestion:
      "Add the required field with a value allowed by schema version 1.",
    fixable: false,
  },
  CFG_INVALID_TYPE: {
    code: "CFG_INVALID_TYPE",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "A field has an invalid JSON type.",
    message:
      "This field has a different type than the configuration contract expects.",
    suggestion: "Replace the value with the expected JSON type.",
    fixable: false,
  },
  CFG_INVALID_VALUE: {
    code: "CFG_INVALID_VALUE",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "A field value is invalid.",
    message: "This value is not allowed by the configuration contract.",
    suggestion: "Use one of the values documented for this field.",
    fixable: false,
  },
  CFG_INVALID_PATH: {
    code: "CFG_INVALID_PATH",
    severity: "error",
    category: "security",
    source: "schema",
    summary: "A project path is unsafe or invalid.",
    message:
      "Project paths must be relative and must not traverse parent directories.",
    suggestion:
      "Use a path inside the project without an absolute prefix or '..'.",
    fixable: false,
  },
  CFG_DUPLICATE_NAME: {
    code: "CFG_DUPLICATE_NAME",
    severity: "error",
    category: "semantic",
    source: "schema",
    summary: "A definition name is duplicated.",
    message: "Definition names must be unique within their namespace.",
    suggestion: "Rename or remove one of the duplicate definitions.",
    fixable: false,
  },
  CFG_TOOL_NAME_INVALID: {
    code: "CFG_TOOL_NAME_INVALID",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "A tool name does not follow the public naming contract.",
    message:
      "Tool names must use snake_case, start with a letter, and be at most 64 characters.",
    suggestion:
      "Rename the tool using lowercase letters, digits, and underscores.",
    fixable: false,
  },
  CFG_DESTRUCTIVE_CONFIRMATION_REQUIRED: {
    code: "CFG_DESTRUCTIVE_CONFIRMATION_REQUIRED",
    severity: "error",
    category: "security",
    source: "schema",
    summary: "A destructive tool does not require confirmation.",
    message: "Destructive tools must require explicit confirmation.",
    suggestion: "Set requiresConfirmation to true for this tool.",
    fixable: true,
  },
  CFG_SECRET_DEFAULT_FORBIDDEN: {
    code: "CFG_SECRET_DEFAULT_FORBIDDEN",
    severity: "error",
    category: "security",
    source: "schema",
    summary: "A secret has an inline default value.",
    message:
      "Secret variables must not store default values in mcp-forge.json.",
    suggestion: "Remove the default and declare an externalSource when needed.",
    fixable: true,
  },
  CFG_KNOWLEDGE_SOURCE_LOCATION_INVALID: {
    code: "CFG_KNOWLEDGE_SOURCE_LOCATION_INVALID",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "A knowledge source uses the wrong location field.",
    message: "Web knowledge sources require url; local sources require path.",
    suggestion:
      "Use url only for web sources and path only for local source types.",
    fixable: false,
  },
  CFG_NPM_VERSION_NOT_PINNED: {
    code: "CFG_NPM_VERSION_NOT_PINNED",
    severity: "error",
    category: "security",
    source: "schema",
    summary: "An npm package version is not pinned.",
    message: "Npm package distributions must use an exact version.",
    suggestion:
      "Replace the floating version with an exact version such as 1.2.3.",
    fixable: false,
  },
  CFG_CLIENT_MODE_INVALID: {
    code: "CFG_CLIENT_MODE_INVALID",
    severity: "error",
    category: "client",
    source: "schema",
    summary: "A client update mode is invalid.",
    message: "The client update mode is not supported.",
    suggestion: "Use preview, merge, or replace-managed-section.",
    fixable: false,
  },
  CFG_VALIDATION_FAILED: {
    code: "CFG_VALIDATION_FAILED",
    severity: "error",
    category: "configuration",
    source: "schema",
    summary: "Configuration validation failed.",
    message: "The configuration does not satisfy schema version 1.",
    suggestion:
      "Review the field and the version 1 configuration documentation.",
    fixable: false,
  },
  SEM_CAPABILITY_DISABLED_WITH_DEFINITIONS: {
    code: "SEM_CAPABILITY_DISABLED_WITH_DEFINITIONS",
    severity: "error",
    category: "semantic",
    source: "semantic",
    summary: "Definitions exist for a disabled MCP capability.",
    message:
      "This capability is disabled but corresponding definitions are present.",
    suggestion: "Enable the capability or remove its definitions.",
    fixable: false,
  },
  SEM_CAPABILITY_ENABLED_WITHOUT_DEFINITIONS: {
    code: "SEM_CAPABILITY_ENABLED_WITHOUT_DEFINITIONS",
    severity: "warning",
    category: "semantic",
    source: "semantic",
    summary: "An MCP capability is enabled without definitions.",
    message: "This capability is enabled but has no corresponding definitions.",
    suggestion: "Add a definition or disable the capability until it is used.",
    fixable: false,
  },
  SEM_KNOWLEDGE_DISABLED_WITH_SOURCES: {
    code: "SEM_KNOWLEDGE_DISABLED_WITH_SOURCES",
    severity: "warning",
    category: "semantic",
    source: "semantic",
    summary: "Knowledge sources are configured while the layer is disabled.",
    message:
      "Knowledge sources will remain unused while knowledge.enabled is false.",
    suggestion:
      "Enable the knowledge layer or remove the unused source declarations.",
    fixable: false,
  },
  SEC_TOOL_WRITE_DISABLED: {
    code: "SEC_TOOL_WRITE_DISABLED",
    severity: "warning",
    category: "security",
    source: "security",
    summary: "A mutating tool conflicts with the global write policy.",
    message:
      "This tool is not read-only while global file writes are disabled.",
    suggestion:
      "Review the tool behavior and explicitly allow writes only if required.",
    fixable: false,
  },
  SEC_TOOL_DELETE_DISABLED: {
    code: "SEC_TOOL_DELETE_DISABLED",
    severity: "warning",
    category: "security",
    source: "security",
    summary: "A destructive tool conflicts with the global delete policy.",
    message: "This tool is destructive while global file deletion is disabled.",
    suggestion:
      "Keep deletion disabled or explicitly allow it after reviewing the tool.",
    fixable: false,
  },
  IMP_UNSUPPORTED_FORMAT: {
    code: "IMP_UNSUPPORTED_FORMAT",
    severity: "error",
    category: "import",
    source: "import",
    summary: "The input format is not supported by an importer.",
    message: "The input does not match a supported MCP configuration format.",
    suggestion: "Provide an LM Studio or generic MCP JSON configuration.",
    fixable: false,
  },
  IMP_AMBIGUOUS_FORMAT: {
    code: "IMP_AMBIGUOUS_FORMAT",
    severity: "error",
    category: "import",
    source: "import",
    summary: "More than one input format matches.",
    message: "The input format is ambiguous and cannot be selected safely.",
    suggestion:
      "Specify sourceKind explicitly or remove conflicting root keys.",
    fixable: false,
  },
  IMP_SERVER_NAME_INVALID: {
    code: "IMP_SERVER_NAME_INVALID",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "A source server name is not portable.",
    message:
      "The source server name requires normalization before it can become a Forge identifier.",
    suggestion: "Review the suggested lowercase kebab-case identifier.",
    fixable: false,
  },
  IMP_SERVER_DEFINITION_INVALID: {
    code: "IMP_SERVER_DEFINITION_INVALID",
    severity: "error",
    category: "import",
    source: "import",
    summary: "A server definition is not a JSON object.",
    message: "Each imported server definition must be a JSON object.",
    suggestion:
      "Replace the server value with an object containing command metadata.",
    fixable: false,
  },
  IMP_COMMAND_MISSING: {
    code: "IMP_COMMAND_MISSING",
    severity: "error",
    category: "import",
    source: "import",
    summary: "A local server command is missing.",
    message: "The imported server does not declare a usable command.",
    suggestion: "Add a non-empty command string to the source definition.",
    fixable: false,
  },
  IMP_ARGS_INVALID: {
    code: "IMP_ARGS_INVALID",
    severity: "error",
    category: "import",
    source: "import",
    summary: "Server arguments are invalid.",
    message: "Imported args must be an array of strings.",
    suggestion: "Replace args with a JSON array containing only strings.",
    fixable: false,
  },
  IMP_ENV_INVALID: {
    code: "IMP_ENV_INVALID",
    severity: "error",
    category: "import",
    source: "import",
    summary: "Environment declarations are invalid.",
    message: "Imported env must be an object whose values are strings.",
    suggestion: "Use string values or remove unsupported environment entries.",
    fixable: false,
  },
  IMP_SECRET_REDACTED: {
    code: "IMP_SECRET_REDACTED",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "A potential secret value was removed.",
    message:
      "A potential secret was detected and redacted from the imported draft.",
    suggestion: "Provide the secret later through an external runtime source.",
    fixable: false,
  },
  IMP_NPM_PACKAGE_DETECTED: {
    code: "IMP_NPM_PACKAGE_DETECTED",
    severity: "info",
    category: "import",
    source: "import",
    summary: "A reliable npx package invocation was detected.",
    message: "The command was normalized as an npm package invocation.",
    fixable: false,
  },
  IMP_NPM_VERSION_MISSING: {
    code: "IMP_NPM_VERSION_MISSING",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "An imported npm package has no version.",
    message: "The detected npm package does not declare a version.",
    suggestion: "Choose and pin an exact package version before installation.",
    fixable: false,
  },
  IMP_NPM_VERSION_NOT_PINNED: {
    code: "IMP_NPM_VERSION_NOT_PINNED",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "An imported npm version is not pinned.",
    message: "The detected npm package uses a floating version or tag.",
    suggestion: "Replace the tag or range with an exact version such as 1.2.3.",
    fixable: false,
  },
  IMP_ABSOLUTE_PATH_REQUIRES_REVIEW: {
    code: "IMP_ABSOLUTE_PATH_REQUIRES_REVIEW",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "An imported path is machine-specific.",
    message:
      "An absolute path was preserved and requires a portability decision.",
    suggestion:
      "Replace it with a project-relative path or an explicit deployment setting.",
    fixable: false,
  },
  IMP_FIELD_INFERRED: {
    code: "IMP_FIELD_INFERRED",
    severity: "info",
    category: "import",
    source: "import",
    summary: "A draft field was inferred rather than observed.",
    message: "One or more draft fields were inferred and require review.",
    suggestion: "Confirm inferred values before producing mcp-forge.json.",
    fixable: false,
  },
  IMP_UNKNOWN_FIELD_PRESERVED: {
    code: "IMP_UNKNOWN_FIELD_PRESERVED",
    severity: "warning",
    category: "import",
    source: "import",
    summary: "Unknown source metadata was preserved separately.",
    message:
      "The source contains unknown fields that were preserved in sanitized raw metadata.",
    suggestion:
      "Review whether the unknown metadata needs explicit importer support.",
    fixable: false,
  },
  IMP_DUPLICATE_SERVER_NAME: {
    code: "IMP_DUPLICATE_SERVER_NAME",
    severity: "error",
    category: "import",
    source: "import",
    summary: "Multiple source names normalize to the same identifier.",
    message:
      "Imported servers would share the same suggested Forge identifier.",
    suggestion: "Choose a unique identifier for each server before conversion.",
    fixable: false,
  },
  TPL_MANIFEST_VERSION_UNSUPPORTED: {
    code: "TPL_MANIFEST_VERSION_UNSUPPORTED",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The template manifest version is unsupported.",
    message: "This template manifest version is not supported.",
    suggestion: 'Use manifestVersion "1" or a compatible Forge version.',
    fixable: false,
  },
  TPL_MANIFEST_INVALID: {
    code: "TPL_MANIFEST_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The template manifest shape is invalid.",
    message: "The template manifest does not satisfy manifest version 1.",
    suggestion: "Review required fields, value types, and unknown properties.",
    fixable: false,
  },
  TPL_TEMPLATE_KIND_UNSUPPORTED: {
    code: "TPL_TEMPLATE_KIND_UNSUPPORTED",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The template kind is reserved but not supported.",
    message: "This template kind is not supported by manifest version 1.",
    suggestion:
      "Use server or knowledge-server for the first template version.",
    fixable: false,
  },
  TPL_TEMPLATE_ID_INVALID: {
    code: "TPL_TEMPLATE_ID_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The template identifier is invalid.",
    message: "Template IDs must use portable lowercase kebab-case.",
    suggestion: "Use lowercase letters, digits, and single hyphens.",
    fixable: false,
  },
  TPL_TEMPLATE_VERSION_INVALID: {
    code: "TPL_TEMPLATE_VERSION_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The template version is invalid.",
    message: "Template versions must be exact semantic versions.",
    suggestion: "Use a version such as 1.0.0 or 1.0.0-beta.1.",
    fixable: false,
  },
  TPL_FILE_PATH_INVALID: {
    code: "TPL_FILE_PATH_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A template target path is unsafe or invalid.",
    message:
      "Template target paths must be portable relative paths inside the project.",
    suggestion:
      "Use forward slashes without absolute prefixes, empty segments, or traversal.",
    fixable: false,
  },
  TPL_SOURCE_PATH_INVALID: {
    code: "TPL_SOURCE_PATH_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A template source path is unsafe or invalid.",
    message:
      "Template source paths must refer to relative content inside the template package.",
    suggestion:
      "Use a portable relative path without URLs, shell syntax, or traversal.",
    fixable: false,
  },
  TPL_DUPLICATE_FILE_PATH: {
    code: "TPL_DUPLICATE_FILE_PATH",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A template target file path is duplicated.",
    message: "Each template target file path must be unique.",
    suggestion: "Remove or rename the duplicate file entry.",
    fixable: false,
  },
  TPL_FILE_DIRECTORY_CONFLICT: {
    code: "TPL_FILE_DIRECTORY_CONFLICT",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A template path is both a file and a directory.",
    message: "Template file and directory declarations conflict.",
    suggestion: "Rename one declaration so every target path has one kind.",
    fixable: false,
  },
  TPL_OWNERSHIP_STRATEGY_INVALID: {
    code: "TPL_OWNERSHIP_STRATEGY_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "File ownership and update strategy are incompatible.",
    message: "This ownership and update strategy combination is not safe.",
    suggestion: "Use the ownership-strategy matrix documented for templates.",
    fixable: false,
  },
  TPL_CONDITION_INVALID: {
    code: "TPL_CONDITION_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A template condition is invalid.",
    message:
      "Template conditions must use a supported operator and normalized configuration field.",
    suggestion:
      "Use one declarative equals or includes condition on a documented field.",
    fixable: false,
  },
  TPL_GENERATED_STATE_INVALID: {
    code: "TPL_GENERATED_STATE_INVALID",
    severity: "error",
    category: "template",
    source: "template",
    summary: "The generated-file state is invalid.",
    message: "The generated-file state does not satisfy state version 1.",
    suggestion: "Review its version, SHA-256 hashes, paths, and file metadata.",
    fixable: false,
  },
  TPL_TEMPLATE_VERSION_MISMATCH: {
    code: "TPL_TEMPLATE_VERSION_MISMATCH",
    severity: "error",
    category: "template",
    source: "template",
    summary: "Generation state belongs to another template version.",
    message:
      "The generation state template identity does not match the selected template.",
    suggestion:
      "Use the matching state or plan an explicit template migration.",
    fixable: false,
  },
  TPL_FILE_MODIFIED: {
    code: "TPL_FILE_MODIFIED",
    severity: "warning",
    category: "template",
    source: "template",
    summary: "A generated file was modified after generation.",
    message:
      "The target content differs from the last known generated content.",
    suggestion: "Review the local changes before regenerating the file.",
    fixable: false,
  },
  TPL_FILE_OWNERSHIP_CONFLICT: {
    code: "TPL_FILE_OWNERSHIP_CONFLICT",
    severity: "error",
    category: "template",
    source: "template",
    summary: "A planned update conflicts with file ownership.",
    message: "The planned operation is not allowed for this file ownership.",
    suggestion:
      "Preserve user-owned content and review shared content manually.",
    fixable: false,
  },
  TPL_MANUAL_REVIEW_REQUIRED: {
    code: "TPL_MANUAL_REVIEW_REQUIRED",
    severity: "warning",
    category: "template",
    source: "template",
    summary: "A template file requires manual review.",
    message:
      "This file cannot be updated automatically by the current planner.",
    suggestion:
      "Review the proposed change without overwriting the target automatically.",
    fixable: false,
  },
  TPL_UNSAFE_REPLACE_BLOCKED: {
    code: "TPL_UNSAFE_REPLACE_BLOCKED",
    severity: "warning",
    category: "template",
    source: "template",
    summary: "An unconditional replacement was blocked.",
    message: "Replacing an existing file requires explicit permission.",
    suggestion:
      "Confirm the controlled replacement only after reviewing the diff.",
    fixable: false,
  },
  GEN_RENDER_REQUEST_INVALID: {
    code: "GEN_RENDER_REQUEST_INVALID",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "The render request is invalid.",
    message:
      "The renderer requires a validated configuration, manifest, and source map.",
    suggestion: "Validate all request inputs before rendering.",
    fixable: false,
  },
  GEN_TEMPLATE_SOURCE_MISSING: {
    code: "GEN_TEMPLATE_SOURCE_MISSING",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A manifest template source is missing.",
    message:
      "No in-memory template source was provided for this manifest file.",
    suggestion: "Provide the exact source path declared by the manifest.",
    fixable: false,
  },
  GEN_TEMPLATE_SOURCE_INVALID: {
    code: "GEN_TEMPLATE_SOURCE_INVALID",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A template source value is invalid.",
    message: "Template source values must be text strings.",
    suggestion: "Replace the source value with an in-memory string.",
    fixable: false,
  },
  GEN_TEMPLATE_SOURCE_UNUSED: {
    code: "GEN_TEMPLATE_SOURCE_UNUSED",
    severity: "warning",
    category: "generation",
    source: "generation",
    summary: "An in-memory template source is unused.",
    message: "This source is not referenced by any manifest file.",
    suggestion: "Remove the source or add the intended manifest file entry.",
    fixable: false,
  },
  GEN_TEMPLATE_SYNTAX_INVALID: {
    code: "GEN_TEMPLATE_SYNTAX_INVALID",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "Template syntax is invalid.",
    message: "The source does not satisfy the restricted template language.",
    suggestion:
      "Use simple values, one supported helper, or balanced if blocks.",
    fixable: false,
  },
  GEN_TEMPLATE_VARIABLE_UNKNOWN: {
    code: "GEN_TEMPLATE_VARIABLE_UNKNOWN",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A template variable is unknown.",
    message: "This variable is not exposed by the safe render context.",
    suggestion: "Use a documented render-context path.",
    fixable: false,
  },
  GEN_TEMPLATE_HELPER_UNKNOWN: {
    code: "GEN_TEMPLATE_HELPER_UNKNOWN",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A template helper is unknown.",
    message: "This helper is not part of the restricted renderer.",
    suggestion:
      "Use json, lowercase, uppercase, kebabCase, snakeCase, or escapeMarkdown.",
    fixable: false,
  },
  GEN_TEMPLATE_CONDITION_INVALID: {
    code: "GEN_TEMPLATE_CONDITION_INVALID",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A render condition cannot be evaluated safely.",
    message:
      "The condition references an unavailable field or unsupported value.",
    suggestion: "Use a documented boolean template or manifest condition.",
    fixable: false,
  },
  GEN_TEMPLATE_RENDER_FAILED: {
    code: "GEN_TEMPLATE_RENDER_FAILED",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "A template source could not be rendered.",
    message: "Rendering failed before a safe output could be produced.",
    suggestion: "Resolve the preceding source diagnostics and render again.",
    fixable: false,
  },
  GEN_OUTPUT_PATH_DUPLICATE: {
    code: "GEN_OUTPUT_PATH_DUPLICATE",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "Multiple rendered files have the same output path.",
    message: "Rendered output paths must be unique.",
    suggestion: "Correct the template manifest before rendering.",
    fixable: false,
  },
  GEN_OUTPUT_CONTENT_INVALID: {
    code: "GEN_OUTPUT_CONTENT_INVALID",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "Rendered output content is invalid.",
    message: "The renderer did not produce a valid text result.",
    suggestion: "Review the source template and helper input.",
    fixable: false,
  },
  GEN_SECRET_ACCESS_BLOCKED: {
    code: "GEN_SECRET_ACCESS_BLOCKED",
    severity: "error",
    category: "generation",
    source: "generation",
    summary: "Template access to secret data was blocked.",
    message:
      "Secret values and secret-source details are not available to templates.",
    suggestion:
      "Render only safe environment metadata such as names and flags.",
    fixable: false,
  },
  GEN_RENDER_SKIPPED_BY_CONDITION: {
    code: "GEN_RENDER_SKIPPED_BY_CONDITION",
    severity: "info",
    category: "generation",
    source: "generation",
    summary: "A manifest file was skipped by its condition.",
    message:
      "The manifest condition was not satisfied, so this file was not rendered.",
    fixable: false,
  },
  PLAN_REQUEST_INVALID: {
    code: "PLAN_REQUEST_INVALID",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "The generation preview request is invalid.",
    message: "The generation preview request cannot be planned safely.",
    suggestion:
      "Provide valid render, manifest, target, and previous-state data.",
    fixable: false,
  },
  PLAN_RENDER_MANIFEST_MISMATCH: {
    code: "PLAN_RENDER_MANIFEST_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Rendered metadata differs from the template manifest.",
    message: "A rendered file does not match its authoritative manifest entry.",
    suggestion: "Render again from the same validated manifest.",
    fixable: false,
  },
  PLAN_RENDER_FILE_MISSING: {
    code: "PLAN_RENDER_FILE_MISSING",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "An active manifest file is missing from rendered output.",
    message:
      "The manifest declares a file that was neither rendered nor conditionally skipped.",
    suggestion: "Resolve the render failure before creating a plan.",
    fixable: false,
  },
  PLAN_RENDER_FILE_UNDECLARED: {
    code: "PLAN_RENDER_FILE_UNDECLARED",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Rendered output contains an undeclared file.",
    message: "A rendered file has no matching manifest entry.",
    suggestion:
      "Declare the file in the manifest or remove it from render output.",
    fixable: false,
  },
  PLAN_TARGET_PATH_DUPLICATE: {
    code: "PLAN_TARGET_PATH_DUPLICATE",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "The target state contains a duplicate path.",
    message: "Each target-state path must be unique.",
    suggestion: "Provide one authoritative target state per path.",
    fixable: false,
  },
  PLAN_PREVIOUS_STATE_PATH_DUPLICATE: {
    code: "PLAN_PREVIOUS_STATE_PATH_DUPLICATE",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "The previous generation state contains a duplicate path.",
    message: "Each previous generated-file path must be unique.",
    suggestion: "Repair or discard the inconsistent previous state.",
    fixable: false,
  },
  PLAN_TEMPLATE_ID_MISMATCH: {
    code: "PLAN_TEMPLATE_ID_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Template IDs do not match.",
    message: "The preview inputs refer to different template IDs.",
    suggestion:
      "Use render output and previous state from the selected template.",
    fixable: false,
  },
  PLAN_TEMPLATE_VERSION_MISMATCH: {
    code: "PLAN_TEMPLATE_VERSION_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Template versions do not match.",
    message: "The preview inputs refer to different template versions.",
    suggestion: "Use matching state or plan an explicit template migration.",
    fixable: false,
  },
  PLAN_OWNERSHIP_MISMATCH: {
    code: "PLAN_OWNERSHIP_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Previous ownership differs from the manifest.",
    message: "Stored file ownership does not match the current manifest.",
    suggestion: "Review the ownership transition before regeneration.",
    fixable: false,
  },
  PLAN_UPDATE_STRATEGY_MISMATCH: {
    code: "PLAN_UPDATE_STRATEGY_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "Previous update strategy differs from the manifest.",
    message: "Stored update strategy does not match the current manifest.",
    suggestion: "Review the strategy transition before regeneration.",
    fixable: false,
  },
  PLAN_TARGET_HASH_MISSING: {
    code: "PLAN_TARGET_HASH_MISSING",
    severity: "warning",
    category: "plan",
    source: "plan",
    summary: "An existing target hash is unavailable.",
    message:
      "The planner cannot verify whether the existing target was modified.",
    suggestion: "Supply its SHA-256 hash before applying an update.",
    fixable: false,
  },
  PLAN_TARGET_MODIFIED: {
    code: "PLAN_TARGET_MODIFIED",
    severity: "warning",
    category: "plan",
    source: "plan",
    summary: "A target changed since the previous generation.",
    message: "The target hash differs from the last generated hash.",
    suggestion: "Review and preserve intentional user changes.",
    fixable: false,
  },
  PLAN_FILE_CONFLICT: {
    code: "PLAN_FILE_CONFLICT",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "A planned file has an unresolved conflict.",
    message: "This file cannot be updated safely from the available state.",
    suggestion:
      "Resolve the hash or ownership conflict before applying a plan.",
    fixable: false,
  },
  PLAN_MANUAL_REVIEW_REQUIRED: {
    code: "PLAN_MANUAL_REVIEW_REQUIRED",
    severity: "warning",
    category: "plan",
    source: "plan",
    summary: "A planned file requires manual review.",
    message: "The current strategy cannot be applied automatically.",
    suggestion: "Review the desired content and target state manually.",
    fixable: false,
  },
  PLAN_EXPLICIT_REPLACE_REQUIRED: {
    code: "PLAN_EXPLICIT_REPLACE_REQUIRED",
    severity: "warning",
    category: "plan",
    source: "plan",
    summary: "Replacing an existing target requires explicit permission.",
    message: "Unconditional replacement is blocked without explicit approval.",
    suggestion:
      "Review the diff and set explicit replace permission if appropriate.",
    fixable: false,
  },
  PLAN_ORPHANED_GENERATED_FILE: {
    code: "PLAN_ORPHANED_GENERATED_FILE",
    severity: "warning",
    category: "plan",
    source: "plan",
    summary: "A previously generated file is no longer in the manifest.",
    message:
      "The orphaned generated file requires a manual keep-or-remove decision.",
    suggestion: "Do not delete it automatically; review it separately.",
    fixable: false,
  },
  PLAN_UNSAFE_ACTION_BLOCKED: {
    code: "PLAN_UNSAFE_ACTION_BLOCKED",
    severity: "error",
    category: "plan",
    source: "plan",
    summary: "An unsafe automatic action was blocked.",
    message: "The planner refused to create an unsafe replacement action.",
    suggestion:
      "Correct inconsistent input or choose an explicit manual workflow.",
    fixable: false,
  },
  PLAN_HASH_MISMATCH: {
    code: "PLAN_HASH_MISMATCH",
    severity: "error",
    category: "plan",
    source: "plan",
    summary:
      "A declared hash does not match rendered content or SHA-256 syntax.",
    message: "The preview cannot trust one of its content hashes.",
    suggestion: "Recompute the hash with the shared SHA-256 helper.",
    fixable: false,
  },
} satisfies Record<ForgeDiagnosticCode, ForgeDiagnosticDefinition>);

export function getDiagnosticDefinition(
  code: ForgeDiagnosticCode,
): ForgeDiagnosticDefinition {
  return DIAGNOSTIC_CATALOG[code];
}
